/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package by.bsuir.pokos.gui.frames;

import by.bsuir.pokos.gui.panels.AddOrderPanel;
import by.bsuir.pokos.gui.panels.OrderPanel;
import by.bsuir.pokos.gui.panels.ShowOrdersPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.tools.Tool;

/**
 *
 * @author Gavrilik
 */
public class WorkerFrame extends javax.swing.JFrame {

    public ObjectOutputStream outputStream;
    public ObjectInputStream inputStream;
    private String workerLogin;
    
    public AddOrderPanel addOrderPanel;
    public ShowOrdersPanel showOrdersPanel;
    public OrderPanel orderPanel;
    
    public WorkerFrame(ObjectOutputStream outputStream,ObjectInputStream inputStream,String login) {
        this.outputStream=outputStream;
        this.inputStream=inputStream;
        this.workerLogin=login;
        initComponents();
        
        orderPanel= new OrderPanel(outputStream, inputStream,workerLogin);
        addOrderPanel = new AddOrderPanel(outputStream,inputStream,workerLogin);
        showOrdersPanel= new ShowOrdersPanel(outputStream,inputStream,this);
        
        dynamicalPane.add(addOrderPanel,BorderLayout.PAGE_START);
        dynamicalPane.add(showOrdersPanel,BorderLayout.PAGE_END);
        dynamicalPane.add(orderPanel,BorderLayout.CENTER);
        
        showOrdersPanel.setVisible(true);
        addOrderPanel.setVisible(false);
        orderPanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addOrderLabel = new javax.swing.JLabel();
        salesOrdersLabel = new javax.swing.JLabel();
        dynamicalPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(61, 139, 212));

        jLabel1.setFont(new java.awt.Font("PT Sans", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/truck-icon.png"))); // NOI18N
        jLabel1.setText("Gavrilik SllS");

        jLabel2.setFont(new java.awt.Font("League Gothic", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Авторизирован:");

        exitLabel.setFont(new java.awt.Font("League Gothic", 0, 22)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit-icon.png"))); // NOI18N
        exitLabel.setText("Выйти");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        loginLabel.setFont(new java.awt.Font("League Gothic", 0, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1234, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginLabel)
                .addGap(290, 290, 290)
                .addComponent(exitLabel)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(exitLabel)
                    .addComponent(loginLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginLabel.setText(workerLogin);

        jDesktopPane1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        addOrderLabel.setBackground(new java.awt.Color(204, 204, 204));
        addOrderLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addOrderLabel.setForeground(new java.awt.Color(115, 115, 115));
        addOrderLabel.setText(" Добавить заказ");
        addOrderLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addOrderLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOrderLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOrderLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addOrderLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addOrderLabelMouseExited(evt);
            }
        });

        salesOrdersLabel.setBackground(new java.awt.Color(204, 204, 204));
        salesOrdersLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        salesOrdersLabel.setForeground(new java.awt.Color(115, 115, 115));
        salesOrdersLabel.setText(" Заказы в реализации");
        salesOrdersLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salesOrdersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesOrdersLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesOrdersLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesOrdersLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addOrderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(salesOrdersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(addOrderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesOrdersLabel)
                .addGap(0, 957, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        dynamicalPane.setBackground(new java.awt.Color(255, 255, 255));
        dynamicalPane.setLayout(new java.awt.BorderLayout());
        jDesktopPane1.add(dynamicalPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jDesktopPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addOrderLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOrderLabelMouseEntered
        // TODO add your handling code here:
         addOrderLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_addOrderLabelMouseEntered

    private void addOrderLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOrderLabelMouseClicked
        // TODO add your handling code here:
        showOrdersPanel.setVisible(false);
        orderPanel.setVisible(false);
        addOrderPanel.setVisible(true);
    }//GEN-LAST:event_addOrderLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        // TODO add your handling code here:
        exitLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        // TODO add your handling code here:
         exitLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitLabelMouseExited

    private void addOrderLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOrderLabelMouseExited
        // TODO add your handling code here:
        addOrderLabel.setForeground(new Color(115,115,115));
        
    }//GEN-LAST:event_addOrderLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
         try {
            outputStream.close();
            inputStream.close();
        } catch (IOException ex) {
            Logger.getLogger(WorkerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainFrame frame =new MainFrame();
        frame.setVisible(true);
        
    }//GEN-LAST:event_exitLabelMouseClicked

    private void salesOrdersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesOrdersLabelMouseClicked
        // TODO add your handling code here:
        addOrderPanel.setVisible(false);
        showOrdersPanel.update_table();
        orderPanel.setVisible(false);
        showOrdersPanel.setVisible(true);
    }//GEN-LAST:event_salesOrdersLabelMouseClicked

    private void salesOrdersLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesOrdersLabelMouseEntered
        // TODO add your handling code here:
        salesOrdersLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_salesOrdersLabelMouseEntered

    private void salesOrdersLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesOrdersLabelMouseExited
        // TODO add your handling code here:
        salesOrdersLabel.setForeground(new Color(115,115,115));
    }//GEN-LAST:event_salesOrdersLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ForwarderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addOrderLabel;
    public javax.swing.JPanel dynamicalPane;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel salesOrdersLabel;
    // End of variables declaration//GEN-END:variables
}
